worker:
  build: .
  dockerfile: Dockerfile.dev
  environment:
    BROKER_URL: "${BROKER_URL}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    DEFAULT_REGION: "us-east-1"
  links:
    - redis:redis
